site_name: Steinie
theme: readthedocs
pages:
  - ["index.md", "Welcome"]
  - ["requests-responses.md", "Using", "Requests and Responses"]
  - ["routers.md", "Using", "Routers"]
  - ["middleware.md", "Using", "Middleware"]
